name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    # - name: Setup Node.js
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: '10.x'
    # - name: npm install | build
    #   run: |
    #     npm ci
    #     npm run build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: build
        BUILD_SCRIPT: npm ci && npm run build